language: c
sudo: required
env:
  global:
    # Travis limits maximum log size, we have to cut tests output 
    - ZFS_TEST_TRAVIS_LOG_MAX_LENGTH=800
  matrix:
    # tags are mainly in ascending order
    - ZFS_TEST_TAGS='zfs_destroy'
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install --yes -qq build-essential autoconf libtool gawk alien fakeroot linux-headers-$(uname -r)
    - sudo apt-get install --yes -qq zlib1g-dev uuid-dev libattr1-dev libblkid-dev libselinux-dev libudev-dev libssl-dev
    # packages for tests
    - sudo apt-get install --yes -qq parted lsscsi ksh attr acl nfs-kernel-server fio
install:
    - git clone --depth=1 https://github.com/zfsonlinux/spl
    - cd spl
    - git checkout master
    - sh autogen.sh
    - ./configure
    - make --no-print-directory -s -j 2
    - cd ..
    - sh autogen.sh
    - ./configure --with-spl=$(pwd)/spl
    - make --no-print-directory -s -j 2
script:
    - sudo ./scripts/zfs.sh
    - sudo ./scripts/zfs-helpers.sh -iv
    - travis_wait 50 ./scripts/zfs-tests.sh -v -T $ZFS_TEST_TAGS
after_failure:
    - find /var/tmp/test_results/current/log -type f -name '*' -printf "%f\n" -exec cut -c -$ZFS_TEST_TRAVIS_LOG_MAX_LENGTH {} \;
after_success:
    - find /var/tmp/test_results/current/log -type f -name '*' -printf "%f\n" -exec cut -c -$ZFS_TEST_TRAVIS_LOG_MAX_LENGTH {} \;
